### ISSUE TITLE
3.0.32: custom extensions with babel/register stopped resolving properly

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#392]
See [mocku](https://github.com/deepsweet/mocku) – `yarn && yarn upgrade esm && yarn start test`. Every single test is failing now because all files are `.ts` and it says "Cannot find module" on them.

It's done through the `@babel/register` with custom extensions array, and `@babel/register` is required after `esm` loader.

Works fine with 3.0.31 and earlier.

**Comment by deepsweet** [comment]
```js
// tmp/wrapper.js
require = require('esm')(module)

require('@babel/register')({
  extensions: ['.ts', '.js']
})
```

```js
// tmp/index.ts
console.log(123)
```

```sh
$ node -r ./tmp/wrapper.js tmp/
```

**Comment by jdalton** [comment]
Thanks @deepsweet!

It's likely related to this change https://github.com/standard-things/esm/commit/024971ecf69f81324c0185ac62d77cda1bb777cf.
In the back of my mind I was wondering if it would cause issues. I'll dig into the root cause and patch and add a test for it.

**Comment by jdalton** [comment]
Ok narrowed it down to https://github.com/standard-things/esm/commit/4cf5770ea0842a055a2edc57d01f2af1ae57997e.

**Comment by jdalton** [comment]
[v3.0.34](https://github.com/standard-things/esm/releases/tag/3.0.34) is released :tada:
