### ISSUE TITLE
3.2.25 does not work with nyc

### ISSUE THREAD

**Issue by screendriver** [standard-things/esm#852]
When I use `esm` together with [nyc](https://github.com/istanbuljs/nyc), [mocha](https://github.com/mochajs/mocha) and [ts-node](https://github.com/TypeStrong/ts-node) (the project is written in [TypeScript](http://www.typescriptlang.org/)) all of my tests fail because it can't find my exported functions anymore: `TypeError: <my-function> is not a function`. When I run my tests without `nyc` it works fine. So the problem only occurs when I use `nyc`. The reason why I create this issue here and not at the `nyc` repository is that when I downgrade `esm` to `3.2.20` it works again. The issue only occurs when I use `3.2.25`

I setup a [small demo repository](https://github.com/screendriver/esm-nyc-bug) where you can reproduce the issue:

1. clone and `yarn install` the repository
1. `yarn test:coverage` gives you the error `TypeError: calc is not a function`
1. downgrade `esm` to `3.2.20` and run it again ➡️ it works without any errors

**Comment by mroderick** [comment]
With a little effort, you can find out exactly which commit was the first bad one (from the perspective of **your** application).

This information will greatly help maintainers understand the issue you're experiencing and will increase the odds of it getting resolved in a timely manner.

1. Check out a copy of `esm` somewhere
1. Use `npm link` in `esm` folder
1. In your project folder, run `npm link esm`
1. In `esm` folder you can now use `git bisect` to determine exactly which commit was the first bad one

See
* https://thoughtbot.com/blog/git-bisect
* https://flaviocopes.com/git-bisect/

Good luck!

**Comment by AndyOGo** [comment]
`nyc -r esm tape test` doesn't collect coverage for me.
If I use `babel-regsiter` it collects coverage correctly 😕 
`nyc -r babel-regsiter tape test` works.

Related PR: https://github.com/AndyOGo/stylelint-declaration-strict-value/pull/64
