### ISSUE TITLE
require hook regression when loading module from node_modules

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#253]
not quite sure on how to start and how to describe the scenario.

in short, the following was working in 0.18.0:
```
node --require @std/esm --require @babel/register --require mymodule index.js
```
and stopped working in 0.19.x.

_mymodule_ is just an ESM module (with import syntax). No other future ecma syntax to be transpiled, though ideally I would like to, just haven't found time to incorporate yet. (not that it matters, the use case is a node.js memory logging module hitting elasticsearch).

this fails  for loading _mymodule_ (**not index.js**) with the following error:
```
TypeError: _b46‍.r is not a function
    at Object.<anonymous> (file:///std-esm-module-test/mymodule/node_modules/cjs/index.js:1)
    at Object.<anonymous> (file:///std-esm-module-test/mymodule/node_modules/cjs/index.js:1)
    at b (file:///std-esm-module-test/node_modules/@std/esm/index.js:1)
    at O._compile (file:///std-esm-module-test/node_modules/@std/esm/index.js:1)
```

this seems to only fail if _mymodule_ requires modules from _node_modules_, otherwise it appears to be working.

I'll write up some simple scenario test cases for the above as well ... probably tomorrow ...

**Comment by jdalton** [comment]
Hi @dnalborczyk!

This looks like a cache mishap. Try deleting your `.cache` folder and reloading. I could get a scenario like `node --require @std/esm --require @babel/register --require mymodule index.js` working but noticed if I mucked up a command that `@babel/register` would cache the untranspiled source. I cleared my `.cache` folder and things worked on the next load.
